#!/bin/bash --login
###
#job name
#SBATCH --job-name=BH_M13
#job stdout file
#SBATCH --output=bench.out.%J
#job stderr file
#SBATCH --error=bench.err.%J
#maximum job time in D-HH:MM
#SBATCH --time=0-72:00
#number of parallel processes (tasks) you are requesting - maps to MPI processes
#SBATCH --ntasks=256
#memory per process in MB 
#SBATCH --mem-per-cpu=4000 
#tasks to run per node (change for hybrid OpenMP/MPI) 
#SBATCH --ntasks-per-node=40
###

cd /home/s.engevabj/config13/M=1.3/

#now run normal batch commands 
module purge
module load hpcw
module load compiler/intel/15.0 mpi/intel/2018/3
#run Intel MPI with mpirun - will automatically pick up Slurm parallel environment
mpirun /home/s.engevabj/codes/FLITE_uns/UnsMgnsg3d >& output

